ECS Engine: System Class Reference
System Class Reference
Base class for all systems in the ECS architecture.
#include <System.hpp>
Public Member Functions
std::set< Entity > getEntities () const
Get all entities currently managed by this system.
virtual void update (float deltaTime)
Update method to be overridden by derived systems.
virtual void render ()
Render method to be overridden by derived systems.
void addDelta (float deltaTime)
Accumulate delta time for time-based execution.
float getDelta () const
Get current accumulated delta time.
bool canExecute () const
Check if system has accumulated enough time to execute.
void setTPS (float tps)
Set the system's execution frequency in ticks per second (TPS)
float getThreshold () const
Get the current execution threshold.
void executeWhenPossible (float deltaTime, std::function< void(float)> task, std::function< void(std::function< void()>)> scheduler)
Execute a task when enough time has accumulated.
Public Attributes
std::set< Entity > entities
Set of entities that match this system's required component signature.
Private Attributes
float _delta = 0.0f
Accumulated delta time since last execution.
float _threshold = 1.0f / 30.0f
Time threshold between executions (default: 1/30 seconds)
std::atomic_bool _isTaskRunning {false}
Flag to prevent concurrent execution of the system.
Detailed Description
Base class for all systems in the ECS architecture.
Systems operate on entities that have specific component signatures. Each system implements logic to process entities with matching components.
Definition at line 21 of file System.hpp.
Member Function Documentation
addDelta()
void System::addDelta (float deltaTime) inline
Accumulate delta time for time-based execution.
Parameters
deltaTime Time to add to the accumulated delta
Definition at line 49 of file System.hpp.
{ _delta += deltaTime; }
References _delta.
Referenced by executeWhenPossible().
canExecute()
bool System::canExecute () const inline
Check if system has accumulated enough time to execute.
Returns
True if system can execute based on its threshold
Definition at line 61 of file System.hpp.
{
        return _delta >= _threshold;
    }
References _delta, and _threshold.
Referenced by executeWhenPossible().
executeWhenPossible()
void System::executeWhenPossible (float deltaTime, std::function< void(float)> task, std::function< void(std::function< void()>)> scheduler) inline
Execute a task when enough time has accumulated.
Parameters
deltaTime Current frame's delta time
task Function to execute when threshold is reached
scheduler Function that schedules the task execution (e.g. thread pool)
This method provides thread-safe execution of system logic based on time thresholds. It prevents multiple concurrent executions of the same system by using atomic flags.
Definition at line 92 of file System.hpp.
{
        addDelta(deltaTime);
        if (canExecute() && !_isTaskRunning.load(std::memory_order_acquire)) {
            _isTaskRunning.store(true, std::memory_order_release);
            float totalDelta = getThreshold();
            scheduler([this, totalDelta, task]() {
                task(totalDelta);
                _isTaskRunning.store(false, std::memory_order_release);
            });
            _delta = 0.0f;
        }
    }
References _delta, _isTaskRunning, addDelta(), canExecute(), and getThreshold().
getDelta()
float System::getDelta () const inline
Get current accumulated delta time.
Returns
Current accumulated delta time in seconds
Definition at line 55 of file System.hpp.
{ return _delta; }
References _delta.
getEntities()
std::set< Entity > System::getEntities () const inline
Get all entities currently managed by this system.
Returns
Set of entity IDs that this system operates on
Definition at line 30 of file System.hpp.
{
        return entities;
    }
References entities.
getThreshold()
float System::getThreshold () const inline
Get the current execution threshold.
Returns
Time threshold between executions in seconds
Definition at line 79 of file System.hpp.
{
        return _threshold;
    }
References _threshold.
Referenced by executeWhenPossible().
render()
virtual void System::render () inline virtual
Render method to be overridden by derived systems.
Definition at line 43 of file System.hpp.
{}
setTPS()
void System::setTPS (float tps) inline
Set the system's execution frequency in ticks per second (TPS)
Parameters
tps Desired execution frequency
This converts the TPS value to a time threshold between executions
Definition at line 71 of file System.hpp.
{
        _threshold = 1.0f / tps;
    }
References _threshold.
update()
virtual void System::update (float deltaTime) inline virtual
Update method to be overridden by derived systems.
Parameters
deltaTime Time elapsed since last update (in seconds)
Definition at line 38 of file System.hpp.
{}
Member Data Documentation
_delta
float System::_delta = 0.0f private
Accumulated delta time since last execution.
Definition at line 111 of file System.hpp.
Referenced by addDelta(), canExecute(), executeWhenPossible(), and getDelta().
_isTaskRunning
std::atomic_bool System::_isTaskRunning {false} private
Flag to prevent concurrent execution of the system.
Definition at line 117 of file System.hpp.
{false};
Referenced by executeWhenPossible().
_threshold
float System::_threshold = 1.0f / 30.0f private
Time threshold between executions (default: 1/30 seconds)
Definition at line 114 of file System.hpp.
Referenced by canExecute(), getThreshold(), and setTPS().
entities
std::set<Entity> System::entities
Set of entities that match this system's required component signature.
Definition at line 24 of file System.hpp.
Referenced by getEntities().
The documentation for this class was generated from the following file:
includes/System.hpp