ECS Engine: ComponentManager Class Reference
ComponentManager Class Reference
Manages component arrays and types.
#include <ComponentManager.hpp>
Public Member Functions
template<typename T >
void registerComponent ()
Registers a component type.
template<typename T >
ComponentTypeID getComponentTypeID ()
Gets the component type ID for a component.
template<typename T >
void addComponent (Entity entity, T component)
Adds a component to an entity.
template<typename T >
void removeComponent (Entity entity)
Removes a component from an entity.
template<typename T >
T & getComponent (Entity entity)
Gets a component from an entity.
void entityDestroyed (Entity entity)
Called when an entity is destroyed.
Private Member Functions
template<typename T >
std::shared_ptr< ComponentStorage< T > > GetComponentStorage ()
Get the Component Storage object.
Private Attributes
std::unordered_map< std::type_index, ComponentTypeID > componentTypes {}
std::unordered_map< std::type_index, std::shared_ptr< AComponentStorage > > ComponentStorages {}
ComponentTypeID nextComponentType {}
Detailed Description
Manages component arrays and types.
Definition at line 15 of file ComponentManager.hpp.
Member Function Documentation
addComponent()
template<typename T > void ComponentManager::addComponent (Entity entity, T component) inline
Adds a component to an entity.
Template Parameters
T Component type.
Parameters
entity The entity.
component The component data.
Definition at line 52 of file ComponentManager.hpp.
        {
            GetComponentStorage<T>()->insertData(entity, component);
        }
References GetComponentStorage().
entityDestroyed()
void ComponentManager::entityDestroyed (Entity entity) inline
Called when an entity is destroyed.
Parameters
entity The destroyed entity.
Definition at line 84 of file ComponentManager.hpp.
        {
            for (auto const& pair : ComponentStorages)
            {
                auto const& component = pair.second;
                component->entityDestroyed(entity);
            }
        }
References ComponentStorages, and GetComponentStorage().
getComponent()
template<typename T > T & ComponentManager::getComponent (Entity entity) inline
Gets a component from an entity.
Template Parameters
T Component type.
Parameters
entity The entity.
Returns
Reference to the component data.
Definition at line 75 of file ComponentManager.hpp.
        {
            return GetComponentStorage<T>()->getData(entity);
        }
References GetComponentStorage().
GetComponentStorage()
template<typename T > std::shared_ptr< ComponentStorage< T > > ComponentManager::GetComponentStorage () inline private
Get the Component Storage object.
Template Parameters
T
Returns
std::shared_ptr<ComponentStorage<T>>
Definition at line 104 of file ComponentManager.hpp.
        {
            std::type_index typeName = typeid(T);
            return std::static_pointer_cast<ComponentStorage<T>>(ComponentStorages[typeName]);
        }
References ComponentStorages, and GetComponentStorage().
Referenced by addComponent(), entityDestroyed(), getComponent(), GetComponentStorage(), and removeComponent().
getComponentTypeID()
template<typename T > ComponentTypeID ComponentManager::getComponentTypeID () inline
Gets the component type ID for a component.
Template Parameters
T Component type.
Returns
The component type ID.
Definition at line 39 of file ComponentManager.hpp.
        {
            std::type_index typeName = typeid(T);
            return componentTypes[typeName];
        }
References componentTypes.
registerComponent()
template<typename T > void ComponentManager::registerComponent () inline
Registers a component type.
Template Parameters
T Component type.
Definition at line 23 of file ComponentManager.hpp.
        {
            std::type_index typeName = typeid(T);
            componentTypes.insert({typeName, nextComponentType});
            ComponentStorages.insert({typeName, std::make_shared<ComponentStorage<T>>()});
            printf("Registering component type %d - (%s)\n", nextComponentType, typeName.name());
            nextComponentType++;
        }
References ComponentStorages, componentTypes, and nextComponentType.
removeComponent()
template<typename T > void ComponentManager::removeComponent (Entity entity) inline
Removes a component from an entity.
Template Parameters
T Component type.
Parameters
entity The entity.
Definition at line 63 of file ComponentManager.hpp.
        {
            GetComponentStorage<T>()->removeData(entity);
        }
References GetComponentStorage().
Member Data Documentation
ComponentStorages
std::unordered_map<std::type_index, std::shared_ptr<AComponentStorage> > ComponentManager::ComponentStorages {} private
Definition at line 95 of file ComponentManager.hpp.
{};
Referenced by entityDestroyed(), GetComponentStorage(), and registerComponent().
componentTypes
std::unordered_map<std::type_index, ComponentTypeID> ComponentManager::componentTypes {} private
Definition at line 94 of file ComponentManager.hpp.
{};
Referenced by getComponentTypeID(), and registerComponent().
nextComponentType
ComponentTypeID ComponentManager::nextComponentType {} private
Definition at line 96 of file ComponentManager.hpp.
{};
Referenced by registerComponent().
The documentation for this class was generated from the following file:
includes/ComponentManager.hpp